name: "Setup pnpm"
description: "Installs node deps with pnpm"

inputs:
  node-version:
    description: node version
    required: true
  pnpm-version:
    description: pnpm version
    required: false
    default: "8"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@ebcfd6995dade4b0104ac774445cef8b3b4635b0
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      shell: bash
